---
name: Python CI & Docker Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.0-alpha - 3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Make
        run: make

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: ghcr.io/cbdq-io/gitchangelog:latest
          scanners: vuln
          trivy-config: trivy.yaml

  build-and-publish:
    runs-on: ubuntu-latest
    needs: setup-and-test
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/')

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tags
        id: docker_tags
        run: |
          REPO=ghcr.io/${{ github.repository_owner }}/gitchangelog
          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "tag=${REPO}:latest" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            echo "tag=${REPO}:${VERSION_TAG}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.docker_tags.outputs.tag }}
